/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;


import Aplicacao.programa;
import CONEXAO_MYSQL.banco_dados_mysql;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme_da_souza
 */
public class CRUD_TELA_LOGIN extends javax.swing.JDialog {
    
    banco_dados_mysql bd = new banco_dados_mysql();

    private boolean senha = false;
    
    private String user;
            
    private boolean tipoUser;

    public boolean isSenha() {
        return senha;
    }

    public void setSenha(boolean senha) {
        this.senha = senha;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public boolean isTipoUser() {
        return tipoUser;
    }

    public void setTipoUser(boolean tipoUser) {
        this.tipoUser = tipoUser;
    }

    /**
     * Creates new form Entrada
     */

    /**
     * Creates new form CRUD_TELA_LOGIN
     */
    public CRUD_TELA_LOGIN(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
       
        jTSENHA.setText(null);
        jLSENHA.setVisible(senha);
        jTSENHA.setVisible(senha);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNOME = new javax.swing.JTextField();
        jLSENHA = new javax.swing.JLabel();
        jBALTERAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTSENHA = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome: ");

        jLSENHA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLSENHA.setText("Senha: ");

        jBALTERAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBALTERAR.setText("User/Adm");
        jBALTERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBALTERARActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilherme_da_souza\\Downloads\\LOGO_NORDIC pequeno.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBALTERAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLSENHA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNOME)
                            .addComponent(jTSENHA)))
                    .addComponent(jLabel4))
                .addGap(18, 128, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSENHA)
                    .addComponent(jTSENHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBALTERAR))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBALTERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBALTERARActionPerformed

        if(senha == false){

            setSenha(true);
            jLSENHA.setVisible(senha);
            jTSENHA.setVisible(senha);

        }else{

            jTSENHA.setText(null);
            setSenha(false);
            jLSENHA.setVisible(senha);
            jTSENHA.setVisible(senha);
        }

    }//GEN-LAST:event_jBALTERARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(bd.getConnection()){

            PreparedStatement stmt = null;
            ResultSet rs = null;

            PreparedStatement stmt2 = null;
            ResultSet rs2 = null;

            if(!isSenha()){

                try{

                    String consulta_adm = "select user_func from funcionario "
                    +"inner join adm "
                    +"where user_func = ? and funcionario.id_func = adm.id_func;";

                    stmt = bd.conexao.prepareStatement(consulta_adm);

                    stmt.setString(1, jTNOME.getText());

                    rs = stmt.executeQuery();

                    if(rs.next() == false){

                        String consulta_funcionario = "select user_func from funcionario "
                        +"where user_func = ?";

                        stmt2 = bd.conexao.prepareStatement(consulta_funcionario);

                        stmt2.setString(1, jTNOME.getText());

                        rs2 = stmt2.executeQuery();

                        if(rs2.next() != false){

                            JOptionPane.showMessageDialog(null, "Usuário Aceito");

                            setUser(jTNOME.getText());
                            
                            setTipoUser(false);

                            bd.conexao.close();

                            this.dispose();

                            programa p1  = new programa(null, true);
                            
                            p1.setVisible(true);

                        }else{

                            JOptionPane.showMessageDialog(null, "Usuário não existe");

                            bd.conexao.close();

                        }

                    }else{

                        JOptionPane.showMessageDialog(null, "Usuário é um adm");

                        setSenha(true);
                        jLSENHA.setVisible(senha);
                        jTSENHA.setVisible(senha);

                        bd.conexao.close();

                    }

                }catch(SQLException error){

                    JOptionPane.showMessageDialog(null, error);

                }

            }else{

                try{

                    String consulta_adm = "select user_func from funcionario "
                    +"inner join adm "
                    +"where user_func = ? and funcionario.id_func = adm.id_func;";

                    stmt = bd.conexao.prepareStatement(consulta_adm);

                    stmt.setString(1, jTNOME.getText());

                    rs = stmt.executeQuery();

                    if(rs.next() == false){

                        String consulta_funcionario = "select user_func from funcionario "
                        +"where user_func = ?";

                        stmt2 = bd.conexao.prepareStatement(consulta_funcionario);

                        stmt2.setString(1, jTNOME.getText());

                        rs2 = stmt2.executeQuery();

                        if(rs2.next() != false){

                            JOptionPane.showMessageDialog(null, "Usuário não possui Adm");

                            jTSENHA.setText(null);
                            setSenha(false);
                            jLSENHA.setVisible(senha);
                            jTSENHA.setVisible(senha);

                            bd.conexao.close();

                        }else{

                            JOptionPane.showMessageDialog(null, "Usuário não existe");

                            bd.conexao.close();

                        }

                    }else{

                        String consulta_funcionario = "select user_func, senha from funcionario "
                        +"inner join adm "
                        +"where user_func = ? and senha = ? and funcionario.id_func = adm.id_func;";

                        stmt2 = bd.conexao.prepareStatement(consulta_funcionario);

                        stmt2.setString(1, jTNOME.getText());
                        stmt2.setString(2, jTSENHA.getText());

                        rs2 = stmt2.executeQuery();

                        if(rs2.next() == false){

                            JOptionPane.showMessageDialog(null, "Senha incorreta");

                            bd.conexao.close();

                        }else{

                            JOptionPane.showMessageDialog(null, "Usuário e Senha aceitos");

                            setUser(jTNOME.getText());

                            setTipoUser(true);


                            bd.conexao.close();

                            this.dispose();

                            programa p1  = new programa(null, true);
                            p1.setVisible(true);

                        }

                    }

                }catch(SQLException error){

                    JOptionPane.showMessageDialog(null, error);

                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUD_TELA_LOGIN dialog = new CRUD_TELA_LOGIN(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBALTERAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLSENHA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNOME;
    private javax.swing.JPasswordField jTSENHA;
    // End of variables declaration//GEN-END:variables
}
